### ISSUE TITLE
Search Bar Task List

### ISSUE THREAD

**Issue by tryn2hard** [dhochman/Skatespot-Organizer#14]
## Description

This issue represents a task list of items that need to be added to the search bar to provide better user-experience when using the app. 

## Items 

- [x] Add animation transition for search bar. The hamburger menu should morph into a back arrow when search is started

- [x] Add a listener for user input during search

- [x] Display the clear icon only when text has been entered into the search 

- [x] Clear the search object when the back arrow has been pressed 

- [x] Move the search bar layout code out of main and into its own xml 

- [x] Add a toolbar to contain the search bar layout 

- [x] Programmatically change the toolbar visibility for each fragment

- [x] Display a transparent toolbar with only the search bar visible for the Map Fragment

- [x] Display a solid toolbar including the search bar for the List Fragment

**Comment by tryn2hard** [comment]
## Progress

The previous list of items was completed; however, with the addition of the tool bar a new task has to be completed. 

## Items

- [ ] Change search icon colors accordingly to the fragment being displayed

**Comment by tryn2hard** [comment]
## Conclusion

Well as unpleasant as that was, we now have icons that change colors to suite the fragment being displayed.

**Comment by tryn2hard** [comment]
## Error

The ClearableAutoTextComplete (our search box) is not changing it's text and hint color according to the visible fragment. Tried changing the theme but that kept crashing the app. Need another way to dynamically change the color of the text and hint when the user navigates between fragments.

**Comment by tryn2hard** [comment]
Also, need to change the hide/show logic to use the container for the search

**Comment by tryn2hard** [comment]
- [ ] Search bar needs to hide the clear button icon ('X') when the user deletes all the text
