### ISSUE TITLE
Settings Task List 

### ISSUE THREAD

**Issue by tryn2hard** [dhochman/Skatespot-Organizer#15]
## Overview

The following issue is to list the tasks to implement the settings through the navigation drawer. 

## Tasks
- [ ] Create a SettingsFragment to be instantiated when the user clicks on the settings option from the Navigation Drawer

- [ ] Have SettingsActivity host the SettingsFragment 

- [ ] Add a Toolbar to display the Settings title and enable "up" button navigation 

- [ ] Create a Settings XML resource to hold the different settings options 
       - Units of measure (miles or kilometers)
       - Use only when connected to wifi 
       - Delete all spots

- [ ] Move "Delete All Spots" Alert Dialog logic from SettingsActivity to SettingsFragment 

- [ ] Create OnPreferenceClickListeners for all the settings options

**Comment by tryn2hard** [comment]
add a text size option

**Comment by tryn2hard** [comment]
add theme light or dark option
