### ISSUE TITLE
Main Activity Clean Up

### ISSUE THREAD

**Issue by tryn2hard** [dhochman/Skatespot-Organizer#17]
## Description

This issue contains the tasks to clean up Main Activity for better readability. 

## Tasks

- [x] Comment all methods, variable declarations, etc.

- [x]  Remove all hard-coded strings to the Strings xml file

- [x]  Remove log unnecessary log statements
