### ISSUE TITLE
Adding Favorites

### ISSUE THREAD

**Issue by tryn2hard** [dhochman/Skatespot-Organizer#19]
## Description

This is a task list for implementing favoriting a spot into the app 

## Task List

- [x] add the necessary drawable resources

- [x] add the imageViews to both the list and grid layouts

- [x] create an onClickListener for the imageView in both grid and list adapters

- [x] make changes to the database to store which spots have been favorited (make sure to take your time and do this right)

- [x] add logic to the adapters to retrieve whether a spot has been added to the favorite list or not 

## Optional
- [ ] add a favorites navigation point to the bottom navigation bar

**Comment by tryn2hard** [comment]
## Progress

Running into a major problem with Room locking up. Update the Room version to get around the problem. See link below

https://stackoverflow.com/questions/50420649/upgrading-room-db-with-migrations-causes-db-lock

**Comment by tryn2hard** [comment]
## Additional Tasks

- [ ] Add the favorite icon to EditSpot Activity 

- [ ] Add logic for user clicks on the favorite icon

**Comment by tryn2hard** [comment]
## Resolution

The following commits have added the favorite implementation to the code base: 
899d087d1bc000ac4268937c443f52f7fc215e53
36e163282ab2a096ac46676a03c51c6d28c645c1 
3db8d76b341cc7427654e74077eb246806b3284a

![](https://media.giphy.com/media/My6uWnBRiQrVC/giphy.gif)
