### ISSUE TITLE
Primary Spot Type Task List

### ISSUE THREAD

**Issue by tryn2hard** [dhochman/Skatespot-Organizer#22]
## Tasks

- [x] Create a String [] to hold the different spot types

- [x] Add a spinner to SpotDetailActivity

- [x] Connect the spinner to the String[] resource using an adapter in the SpotDetailActivity

- [x] Detect when a item has been selected by using OnItemSelectedListener()

- [x] Update the spot with the new spot type using livedata

- [x] During init of SpotDetailActivity make sure to get the correct spot type and set the position of the spinner accordingly 

- [x] Add checks for new spot types with no type selected 

## Additional Tasks

- [x] In MapFragment, add code to display the correct marker based on the primary spot type

**Comment by tryn2hard** [comment]
Also added another marker image for skateparks.
